import { CSSProperties } from 'react'
import colors from '../../constants/colors'

export const styles: { [key: string]: CSSProperties } = {
  //
  rowHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    height: 40,
    borderBlockWidth: 1,
    paddingBottom: 10,
    borderBottomStyle: 'solid',
    borderBlockColor: colors.border,
  },
  buttonHeader: {
    paddingRight: 20,
    paddingLeft: 20,
    height: '100%',
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.red,
  },
  //
  rowFooter: {
    marginTop: 10,
    display: 'flex',
    justifyContent: 'space-between',
    height: 40,
    gap: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  buttonFooter: {
    width: 100,
    height: '100%',
    backgroundColor: colors.yellow,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 16,
    color: colors.black,
  },
  //
  createModal: {
    maxWidth: '100%',
    height: '100%',
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-end',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  chartInput: {
    backgroundColor: colors.greyhard,
    height: 40,
    minHeight: 40,
    borderRadius: 8,
    color: colors.white,
    border: 'none',
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chartInputTitle: {
    color: colors.grey,
    display: 'flex',
    flex: 1,
    margin: 0,
  },
  input: {
    flex: 3,
    height: 40,
    marginBottom: 10,
    padding: 10,
    fontSize: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.greyhard,
    color: colors.white,
  },
  switch: {
    height: 40,
    width: 80,
    border: 'none',
    borderRadius: 20,
    position: 'relative',
    padding: 4,
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
}
