import { CSSProperties } from 'react'
import colors from '../../constants/colors'

export const styles: { [key: string]: CSSProperties } = {
  column: {
    width: '100%',
    position: 'inherit',
    height: '100%',
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
    marginBottom: 10,
  },
  scroll: {
    flexDirection: 'column',
    display: 'flex',
    gap: 10,
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  quizItem: {
    width: '100%',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: 8,
    padding: 10,
    gap: 5,
    display: 'flex',
    boxSizing: 'border-box',
    flexDirection: 'column',
  },
  localLanguageButton: {
    paddingRight: 20,
    paddingLeft: 20,
    height: 40,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.red,
    marginRight: 10,
    marginBottom: 10,
  },
  quizItemTitle: {
    fontSize: 20,
    color: colors.white,
    fontWeight: 'bold',
    margin: 0,
    marginBottom: 10,
    flex: 1,
  },
  quizItemButton: {
    fontSize: 18,
    color: colors.white,
    margin: 0,
  },
  editButton: {
    height: 30,
    width: 60,
    backgroundColor: colors.greyhard,
    color: colors.white,
    borderRadius: 5,
    border: 'none',
  },
  quizEditor: {
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    padding: 10,
    borderRadius: 8,
  },
  input: {
    height: 40,
    width: '100%',
    boxSizing: 'border-box',
    padding: 10,
    marginBottom: 10,
    borderRadius: 5,
    border: '1px solid ' + colors.border,
    backgroundColor: colors.greyhard,
    color: colors.white,
  },
  answerButton: {
    height: 40,
    width: 40,
    borderRadius: 5,
    backgroundColor: colors.greyhard,
    border: '1px solid ' + colors.border,
    cursor: 'pointer',
  },
  addButton: {
    height: 40,
    width: 100,
    backgroundColor: colors.white,
    color: colors.black,
    fontSize: 16,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
  },
  saveButton: {
    height: 40,
    width: 100,
    backgroundColor: colors.yellow,
    color: colors.black,
    fontSize: 16,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    marginLeft: 10,
  },
  cancelButton: {
    height: 40,
    width: 100,
    backgroundColor: 'transparent',
    color: colors.red,
    fontSize: 16,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    marginLeft: 10,
  },
  createButton: {
    marginBottom: 10,
    height: 40,
    width: 100,
    backgroundColor: colors.white,
    color: colors.black,
    fontSize: 16,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
  },
}
