import { CSSProperties } from 'react'
import colors from '../constants/colors'

export const styles: { [key: string]: CSSProperties } = {
  column: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  row: {
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    width: '100%',
  },
  input: {
    flex: 3,
    minHeight: 40,
    maxHeight: 100,
    height: 40,
    marginBottom: 10,
    padding: 10,
    fontSize: 18,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.greyhard,
    color: colors.white,
  },
  comment: {
    margin: 0,
    flex: 3,
    textAlign: 'left',
    color: colors.grey,
  },
  //
  rowHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    height: 40,
    borderBlockWidth: 1,
    paddingBottom: 10,
    borderBottomStyle: 'solid',
    borderBlockColor: colors.border,
  },
  buttonHeader: {
    paddingRight: 20,
    paddingLeft: 20,
    height: '100%',
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 16,
    color: colors.black,
    backgroundColor: colors.red,
  },
  //
  rowFooter: {
    marginTop: 10,
    display: 'flex',
    justifyContent: 'space-between',
    height: 40,
    gap: 10,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingTop: 10,
  },
  buttonFooter: {
    width: 100,
    height: '100%',
    backgroundColor: colors.yellow,
    border: 'none',
    borderRadius: 5,
    cursor: 'pointer',
    fontSize: 16,
    color: colors.black,
  },
}
